ARG BASE_IMAGE_TAG='9.6'
########################################

FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

RUN dnf install -y \
    ipa-client \
    certmonger \
    NetworkManager \
    NetworkManager-wifi \
    wpa_supplicant \
    && dnf clean all

COPY files/ /

RUN mkdir -p /etc/pki/tls/private /etc/pki/tls/certs && \
    chmod 755 /etc/pki/tls/certs && \
    chmod 700 /etc/pki/tls/private

RUN chmod +x /usr/local/sbin/* && \
    chmod +x /etc/NetworkManager/dispatcher.d/99-802.1x-cert && \
    systemctl enable certmonger && \
    ln -s /usr/lib/systemd/system/idm-enroll.service/etc/systemd/system/multi-user.target.wants/idm-enroll.service
