
ARG BASE_IMAGE_TAG='9.6'
########################################

FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

RUN dnf install -y \
    ipa-server \
    ipa-server-dns \
    ipa-server-trust-ad \
    bind \
    bind-dyndb-ldap \
    certmonger \
    NetworkManager \
    firewalld \
    && dnf clean all

COPY files/ /

RUN mkdir -p /etc/pki/tls/private /etc/pki/tls/certs && \
    chmod 755 /etc/pki/tls/certs && \
    chmod 700 /etc/pki/tls/private

# Ensure a writable path exists for IPA HTML files
RUN mkdir -p /var/lib/ipa/html /usr/share/ipa/html

RUN chmod +x /usr/local/sbin/* && \
    ln -s /usr/lib/systemd/system/file-monitor.service /etc/systemd/system/multi-user.target.wants/file-monitor.service && \
    systemctl enable certmonger && \
    systemctl enable firewalld && \
    systemctl enable usr-share-ipa-html.mount && \
    systemctl enable idm-server-install.service

