FROM quay.io/fedora/fedora-bootc:42

# Include bootc-image-builder customization (mainly to include default rootfs)
RUN mkdir -p /usr/lib/bootc/install  
COPY builder-customizations.toml /usr/lib/bootc/install/10-custom-builder.toml

# Package dependencies for building
RUN dnf install -y curl dnf-plugins-core langpacks-en glibc-langpack-en \
    'dnf-command(config-manager)' && \
    dnf clean all

# Install dnf5 copr plugin and enable COPR repository for ROS2 on Fedora 42
RUN dnf install -y 'dnf5-command(copr)' && \
    dnf copr enable -y tavie/ros2 && \
    dnf clean all

# (OPTIONAL) Install dev packages
#RUN dnf install -y cmake \
#    gcc-c++ \
#    git \
#    make \
#    patch \
#    python3-colcon-common-extensions \
#    python3-mypy \
#    python3-pip \
#    python3-pytest \
#    python3-pytest-repeat \
#    python3-pytest-rerunfailures \
#    python3-rosdep \
#    python3-setuptools \
#    python3-vcstool \
#    wget && \
#    python3 -m pip install -U --user \
#        flake8-blind-except==0.1.1 \
#        flake8-class-newline \
#        flake8-deprecated && \
#    dnf clean all

# Install additional dependencies
RUN dnf install -y \
    spdlog-devel \
    lttng-ust \
    python3-typing-extensions \
    python3-numpy \
    python3-packaging \
    python3-psutil \
    python3-lark-parser \
    console-bridge-devel && \
    dnf clean all

# Install ROS from COPR to a temporary location 
RUN dnf install -y  --use-host-config  ros-kilted-desktop  && \
    dnf clean all

RUN echo "source /usr/lib64/ros2-kilted/setup.bash" >> /etc/bashrc 