FROM ghcr.io/luisarizmendi/bootc-rhel-jetson:latest


########### CUSTOMIZATIONS ###########
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install pciutils usbutils python3-pip podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service 


### Copy files
COPY files/ /

## Include WIFI config
RUN --mount=type=secret,id=WIFI_SSID --mount=type=secret,id=WIFI_PASSWORD \
    sed -i 's/YOUR_WIFI_NAME/$(cat /run/secrets/WIFI_SSID | tr -d '\n')/g' /etc/NetworkManager/system-connections/wifi.nmconnection  && \
    sed -i 's/YOUR_WIFI_PASSWORD/$(cat /run/secrets/WIFI_PASSWORD | tr -d '\n')/g' /etc/NetworkManager/system-connections/wifi.nmconnection

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    ln -s /etc/systemd/system/mac-hostname.service /etc/systemd/system/multi-user.target.wants/mac-hostname.service && \
    mkdir -p /etc/models

# Pull model from OCI registry
#COPY --from=quay.io/luisarizmendi/modelcar-hardhat:v1 /models/ /etc/models
COPY --from=quay.io/luisarizmendi/modelcar-hardhat:v2 /models/ /etc/models

