#ARG BASE_IMAGE_RELEASE='9'
#ARG BASE_IMAGE_TAG='9.6'

ARG BASE_IMAGE_RELEASE='10'
ARG BASE_IMAGE_TAG='10.2'

FROM registry.redhat.io/rhel${BASE_IMAGE_RELEASE}/rhel-bootc:${BASE_IMAGE_TAG}

##ARG BASE_IMAGE_RELEASE='9'
##ARG RHEM_RELEASE='1.1'
#
#ARG BASE_IMAGE_RELEASE='10'
#ARG RHEM_RELEASE='1.3'
#
################################################################################
#Red Hat Edge Manager
################################################################################

#RUN dnf config-manager \
#        --set-enabled edge-manager-${RHEM_RELEASE}-for-rhel-${BASE_IMAGE_RELEASE}-$(uname -m)-rpms && \
#    dnf -y install flightctl-agent flightctl-cli && \
#    dnf -y clean all && \
#    systemctl enable flightctl-agent.service && \
#    systemctl mask bootc-fetch-apply-updates.timer 
#
## Optional: To enable podman-compose application support, uncomment below
# RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${BASE_IMAGE_RELEASE}.noarch.rpm && \
#     dnf -y install podman-compose && \
#     dnf -y clean all && \
#     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
#     systemctl enable podman.service


################################################################################
# Customization
################################################################################

RUN useradd -m -d /var/home/kiosk kiosk 

RUN dnf install -y yq stress shadow-utils gnome-kiosk gdm gnome-kiosk-script-session  git firefox \
    && dnf clean all

RUN mkdir -p /var/home/kiosk/.local/bin/ /etc/accountsservice/user-templates /etc/gdm/

COPY files/ /

RUN chmod +x /var/home/kiosk/.local/bin/gnome-kiosk-script && \
    chown -R kiosk:kiosk /var/home/kiosk && \
    chmod +x /usr/local/bin/* && \
    ln -s /usr/lib/systemd/system/first-boot.service /etc/systemd/system/multi-user.target.wants/first-boot.service && \
    ln -s /usr/lib/systemd/system/hook-files.service /etc/systemd/system/multi-user.target.wants/hook-files.service

RUN systemctl set-default graphical.target

#////////////////////////////////////////
#DEMO V2 update (tmux )
#////////////////////////////////////////
RUN dnf install -y tmux && \
    dnf clean all
#////////////////////////////////////////
