FROM registry.redhat.io/rhel9/rhel-bootc:9.6

# Real-Time
#################################################
# ARGUMENTOS POR DEFECTO
#################################################

# CPUs dedicadas a RT
ARG RTCPU_LIST=1

# Perfil tuned por defecto
ARG TARGET_PROFILE=realtime

# Kernel args extra para RT y ROS2
ARG EXTRA_KARGS="isolcpus=1 nohz_full=1 rcu_nocbs=1 intel_pstate=disable processor.max_cstate=1"


#################################################
# REALTIME KERNEL
#################################################

RUN dnf -y install 'dnf-command(config-manager)'

RUN ARCH=$(uname -m) && \
    case "$ARCH" in \
        x86_64) RT_REPO="rhel-9-for-x86_64-rt-kernel-rpms" ;; \
        aarch64) RT_REPO="rhel-9-for-aarch64-rt-kernel-rpms" ;; \
        *) echo "Unsupported architecture: $ARCH" && exit 1 ;; \
    esac && \
    dnf config-manager --set-enabled $RT_REPO

RUN rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-core \
    --install kernel-rt-core \
    --install kernel-rt-modules \
    --install kernel-rt-kvm

#################################################
# REALTIME PACKAGES
#################################################

RUN dnf install -y \
    tuned \
    tuned-profiles-nfv \
    realtime-tests \
    rtla \
    stress-ng \
    trace-cmd \
    hwloc \
    tmux

RUN systemctl enable tuned
RUN systemctl disable irqbalance

#################################################
# REALTIME BOOT PARAMETERS MULTI-ARCH
#################################################

RUN rm -f /usr/lib/bootc/kargs.d/*.toml ;\
  # x86_64 kargs
  echo -e "kargs=[\"iommu=pt\"]\nmatch-architectures=[\"x86_64\"]" \
      > /usr/lib/bootc/kargs.d/01-iommu-x86.toml ; \
  echo -e "kargs=[\"intel_iommu=on\"]\nmatch-architectures=[\"x86_64\"]" \
      > /usr/lib/bootc/kargs.d/02-intel-iommu-x86.toml ; \
  echo -e "kargs=[\"idle=poll\"]\nmatch-architectures=[\"x86_64\"]" \
      > /usr/lib/bootc/kargs.d/03-idle-x86.toml ; \
  echo -e "kargs=[\"rcutree.nocb_patience_delay=1000\"]\nmatch-architectures=[\"x86_64\"]" \
      > /usr/lib/bootc/kargs.d/04-rcu-x86.toml ; \
  echo -e "kargs=[\"console=ttyS1,115200\"]\nmatch-architectures=[\"x86_64\"]" \
      > /usr/lib/bootc/kargs.d/05-console-x86.toml ; \
  # aarch64 kargs
  echo -e "kargs=[\"idle=poll\"]\nmatch-architectures=[\"aarch64\"]" \
      > /usr/lib/bootc/kargs.d/03-idle-arm.toml ; \
  echo -e "kargs=[\"rcutree.nocb_patience_delay=1000\"]\nmatch-architectures=[\"aarch64\"]" \
      > /usr/lib/bootc/kargs.d/04-rcu-arm.toml ; \
  echo -e "kargs=[\"console=tty0 console=ttyAMA0,115200n81\"]\nmatch-architectures=[\"aarch64\"]" \
      > /usr/lib/bootc/kargs.d/05-console-arm.toml ; \
  # extra args aplicable a cualquier arquitectura
  echo -e "kargs=[\"${EXTRA_KARGS}\"]" \
      > /usr/lib/bootc/kargs.d/99-extra-kargs.toml

#################################################
# REALTIME TUNING (FIRST BOOT)
#################################################

COPY rt-tuning-first-boot.sh /usr/local/sbin/custom-rt-tuning-first-boot.sh
RUN chmod +x /usr/local/sbin/custom-rt-tuning-first-boot.sh

COPY rt-post-install-tuning.service /usr/lib/systemd/system/rt-post-install-tuning.service
RUN systemctl enable rt-post-install-tuning

# Reemplaza placeholder por el profile real
RUN sed -i "s/<profile_name>/${TARGET_PROFILE}/" \
    /usr/local/sbin/custom-rt-tuning-first-boot.sh

# Configura CPUs aisladas en el profile
RUN sed -i "s/^isolated_cores.*/isolated_cores=${RTCPU_LIST}/" \
    /etc/tuned/${TARGET_PROFILE}-variables.conf



#####################################################################################################################################################






# Install basic dependencies (without ROS-specific stuff)
RUN dnf install -y curl tmux xorg-x11-xauth dnf-plugins-core langpacks-en glibc-langpack-en \
    'dnf-command(config-manager)' \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm && \
    env FORCE_DNF=1 crb enable && \
    dnf clean all

# Install ROS repository configuration for potential future updates
RUN dnf install -y "https://github.com/ros-infrastructure/ros-apt-source/releases/download/$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')/ros2-release-$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')-1.noarch.rpm"

# Add ROS repository configuration
RUN tee /etc/yum.repos.d/ros2.repo <<'EOF'
[ros2]
name=ROS 2 - $basearch
enabled=1
baseurl=http://packages.ros.org/ros2/rhel/9/$basearch/
gpgcheck=0
repo_gpgcheck=0

[ros2-debug]
name=ROS 2 - $basearch Debug
enabled=0
baseurl=http://packages.ros.org/ros2/rhel/9/$basearch/debug/
gpgcheck=0
repo_gpgcheck=0

[ros2-source]
name=ROS 2 - Source
enabled=0
baseurl=http://packages.ros.org/ros2/rhel/9/SRPMS/
gpgcheck=0
repo_gpgcheck=0
EOF

# Install ROS dependencies that might be needed at runtime
RUN dnf install -y \
    spdlog-devel \
    lttng-ust \
    python3-typing-extensions \
    python3-numpy \
    python3-packaging \
    python3-psutil \
    python3-lark-parser \
    console-bridge-devel && \
    dnf clean all

# Install ROS desktop to default location (/opt)
RUN dnf install -y --releasever=9 ros-kilted-desktop && \
    dnf clean all

RUN echo "source /opt/ros/kilted/setup.bash" >> /etc/bashrc 


# (OPTIONAL) Uncomment if you need dev packages
RUN dnf install -y cmake \
    gcc-c++ \
    git \
    make \
    patch \
    python3-colcon-common-extensions \
    python3-mypy \
    python3-pip \
    python3-pytest \
    python3-pytest-repeat \
    python3-pytest-rerunfailures \
    python3-rosdep \
    python3-setuptools \
    python3-vcstool \
    wget && \
    python3 -m pip install -U --user \
    flake8-blind-except==0.1.1 \
    flake8-class-newline \
    flake8-deprecated


RUN sed -i 's/^#\?X11Forwarding.*/X11Forwarding yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?X11DisplayOffset.*/X11DisplayOffset 10/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?X11UseLocalhost.*/X11UseLocalhost yes/' /etc/ssh/sshd_config
