AMQ_PROTOCOL=mqtt

AMQ_USER=edgeai
AMQ_PASSWORD=CHANGE_ME_use_a_secret_or_vault_injected_value
AMQ_ROLE=admin
AMQ_NAME=edge-mqtt-broker

# Pre-create addresses for the AI event topics you'll publish to.
AMQ_ADDRESSES=telemetry/inference,telemetry/alerts,telemetry/health

AMQ_GLOBAL_MAX_SIZE=100mb
