ARG BASE_IMAGE_RELEASE='9'
ARG BASE_IMAGE_TAG='9.6'
ARG RHEM_RELEASE='1.1'

#ARG BASE_IMAGE_RELEASE='10'
#ARG BASE_IMAGE_TAG='10.2'
#ARG RHEM_RELEASE='1.2'

FROM registry.redhat.io/rhel${BASE_IMAGE_RELEASE}/rhel-bootc:${BASE_IMAGE_TAG}


################################################################################
#Red Hat Edge Manager
################################################################################

RUN dnf config-manager \
        --set-enabled edge-manager-${RHEM_RELEASE}-for-rhel-${BASE_IMAGE_RELEASE}-$(uname -m)-rpms && \
    dnf -y install flightctl-agent flightctl-cli && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer 

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${BASE_IMAGE_RELEASE}.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

################################################################################
# Customization
################################################################################

RUN useradd -m -d /var/home/kiosk kiosk 

RUN dnf install -y yq stress shadow-utils gnome-kiosk gdm gnome-kiosk-script-session  git firefox \
    && dnf clean all

RUN mkdir -p /var/home/kiosk/.local/bin/ /etc/accountsservice/user-templates /etc/gdm/

COPY files/ /

RUN chmod +x /var/home/kiosk/.local/bin/gnome-kiosk-script && \
    chown -R kiosk:kiosk /var/home/kiosk && \
    chmod +x /usr/local/bin/* && \
    ln -s /usr/lib/systemd/system/first-boot.service /etc/systemd/system/multi-user.target.wants/first-boot.service && \
    ln -s /usr/lib/systemd/system/hook-files.service /etc/systemd/system/multi-user.target.wants/hook-files.service

RUN systemctl set-default graphical.target


###########    EMBED IMAGES  


# Extracts the list of MicroShift container image dependencies
ENV IMAGE_STORAGE_DIR=/usr/lib/containers/storage
ENV IMAGE_LIST_FILE=${IMAGE_STORAGE_DIR}/image-list.txt
ENV IMAGES="quay.io/luisarizmendi/tailwind-pos:latest"


RUN --mount=type=secret,id=PULL_SECRET,dst=/run/secrets/pull-secret.json \
    images="${IMAGES}" ; \
    mkdir -p "${IMAGE_STORAGE_DIR}" ; \
    for img in ${images} ; do \
        sha="$(echo "${img}" | sha256sum | awk '{print $1}')" ; \
        skopeo copy --all --preserve-digests \
            --authfile /run/secrets/pull-secret.json \
            "docker://${img}" "dir:$IMAGE_STORAGE_DIR/${sha}" ; \
        echo "${img},${sha}" >> "${IMAGE_LIST_FILE}" ; \
    done

# Copy container images from the custom directory to the main container storage
RUN cat > /usr/bin/copy-embedded-images <<EOF
#!/bin/bash
set -eux -o pipefail
while IFS="," read -r img sha ; do
    skopeo copy --preserve-digests \
        "dir:${IMAGE_STORAGE_DIR}/\${sha}" \
        "containers-storage:\${img}"
done < "${IMAGE_LIST_FILE}"
EOF

RUN chmod 755 /usr/bin/copy-embedded-images && \
    mkdir -p /usr/lib/systemd/system/microshift.service.d

RUN cat > /usr/lib/systemd/system/microshift.service.d/copy-embedded-images.conf <<EOF
[Service]
ExecStartPre=/usr/bin/copy-embedded-images
EOF



