[storage]
driver = "overlay"
runroot = "/run/user/1000/containers"
graphRoot = "/var/home/detector/.local/share/containers/storage"

[storage.options]
additionalimagestores = ["/var/lib/shared"]

[storage.options.overlay]
ignore_chown_errors = "true"
mount_program = ""
mountopt = "nodev,metacopy=on"