FROM registry.redhat.io/rhel9/rhel-bootc:9.6

## v3 move to rhel 10 ##########################################
#FROM registry.redhat.io/rhel10/rhel-bootc:10.1
################################################

RUN dnf install -y greenboot greenboot-default-health-checks && \
    dnf clean all

COPY files/ /

RUN chmod +x /usr/local/bin/* && \
    systemctl enable first-boot.service

##   v2 remove tcpdump ########################################
RUN dnf install -y tcpdump && \
    dnf clean all
########################################

##   v3 add tree ########################################
#RUN dnf install -y tree && \
#    dnf clean all 
################################################