FROM registry.redhat.io/rhel9/rhel-bootc:9.6

 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm


RUN dnf install -y \
    cockpit \
    cockpit-bridge \
    cockpit-machines \
    cockpit-storaged \
    cockpit-ostree \
    cockpit-pcp \
    python3-pcp \
    cockpit-system \
    cockpit-ws \
    libvirt \
    libvirt-dbus \
    qemu-img \
    qemu-kvm \
    biosdevname \
    qemu-kvm-device-usb-host \
    virt-install \
    setroubleshoot-server \
    dbus-tools \
    tuned \
    irqbalance \
    dialog \
    ncurses \
    novnc-1.4.0 \
    exfatprogs \
    insights-client \
    redhat-release-eula \
    rsyslog \
    nftables \
    cronie \
    scap-security-guide-0.1.74 \
    openscap-1.3.10 \
    openscap-scanner-1.3.10 \
    && dnf clean all