# Builds a basic RHEL Bootc image for NVIDIA Tegra SOC with Nvidia CDI enabled
ARG BASE=registry.redhat.io/rhel9/rhel-bootc:9.7
FROM ${BASE} AS build

RUN export KVER=$(rpm -q --queryformat "%{VERSION}-%{RELEASE}" kernel) && \
  dnf install -y \
    createrepo \
    g++ \
    git-lfs \
    kernel-devel-${KVER} \
    kernel-headers-${KVER} \
    make \
    python3-devel \
    python3-rpm-macros \
    rpmdevtools \
    yum-utils

# Build Jetpack drivers using the BootC Image Kernel version
RUN --mount=type=secret,id=GITLAB_TOKEN \
    export QA_RPATHS=$(( 0x0001|0x0010 )) && \
    export XDG_CONFIG_HOME=$(mktemp -d) && \
    mkdir -p $XDG_CONFIG_HOME/git && \
    echo "https://dummy:$(cat /run/secrets/GITLAB_TOKEN | tr -d '\n')@gitlab.com" \
    > $XDG_CONFIG_HOME/git/credentials && \
    git config --global credential.helper store && \
    git lfs install && \
    git clone https://gitlab.com/redhat/rhel/sst/orin-sidecar/nvidia-jetson-sidecar.git /src && \
    sed -i "s|git@gitlab.com:|https://gitlab.com/|" /src/.gitmodules && \
    make -C /src clean && \
    make -C /src kmod-srpm kmod-rpm && \
    make -C /src jetpack-srpms jetpack-rpms && \
    rm -r $XDG_CONFIG_HOME

# The packages from NVIDIA's repo are only built for specific versions of RHEL, be sure to pin the exact tag
FROM ${BASE}

# Install NVIDIA jetpack components
RUN --mount=from=build,target=/build \
     dnf -y install bsdtar && \
     dnf -y install /build/src/rpmbuild/RPMS/aarch64/*.rpm && \
     dnf clean all

# Regenerate initrd (just in case)
RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver

# Install NVIDIA container toolkit
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
     tee /etc/yum.repos.d/nvidia-container-toolkit.repo && \
     dnf -y install nvidia-container-toolkit && \
     dnf clean all

# Create and enable a systemd service to generate the NVIDIA CDI YAML file
RUN cat <<EOF > /etc/systemd/system/nvidia-cdi.service
[Unit]
Description=Generate the nvidia cdi yaml file
Requires=multi-user.target
Requires=systemd-modules-load.service
After=multi-user.target
After=systemd-modules-load.service

[Service]
Type=oneshot
ExecStartPre=bash -c "echo 1 > /dev/nvgpu/igpu0/power"
ExecStart=nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
RUN systemctl enable nvidia-cdi

# Modify bootc-generic-growpart service to remove virtualization condition
# so that the root partition is expanded to fill the entire disk
RUN sed -i '/ConditionVirtualization=vm/d' /usr/lib/systemd/system/bootc-generic-growpart.service

# Load the i2c-dev kernel module at boot
# for jetson_stats
RUN cat <<EOF > /etc/modules-load.d/i2c-dev.conf
i2c-dev
EOF

# Add kernel arguments for Jetson devices
# disable selinux, and set the correct console device
RUN cat <<EOF > /usr/lib/bootc/kargs.d/10-jetson.toml
kargs = ["enforcing=0", "console=ttyTCU0,115200"]
EOF

##########

# Additional packages
RUN dnf -y install \
            tmux \
            git

### Copy files
COPY files/ /

## Include WIFI config
#RUN --mount=type=secret,id=WIFI_SSID --mount=type=secret,id=WIFI_PASSWORD \
#    sed -i "s/YOUR_WIFI_NAME/$(cat /run/secrets/WIFI_SSID | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection  && \
#    sed -i "s/YOUR_WIFI_PASSWORD/$(cat /run/secrets/WIFI_PASSWORD | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    ln -s /etc/systemd/system/mac-hostname.service /etc/systemd/system/multi-user.target.wants/mac-hostname.service
