# Builds a basic RHEL Bootc image for NVIDIA Tegra SOC with Nvidia CDI enabled

# The packages from NVIDIA's repo are only built for specific versions of RHEL, be sure to pin the exact tag
FROM registry.redhat.io/rhel9/rhel-bootc:9.4-1730828483

# Install NVIDIA jetpack components
# Mask nvpower.service (causes kernel panic)
# Remove upstream host1x kernel module (conflicts with nvidia provided one)

# Container image with nvidia jetson RPMs
COPY --from=quay.io/luisarizmendi/rhel-nvidia-jetson-rpms:9.4 /artifacts/ /tmp/artifact/

RUN dnf -y install /tmp/artifact/*.rpm && \
    dnf clean all && \
    systemctl mask nvfancontrol.service nvpmodel.service nvpower.service && \
    rm -r /tmp/artifact && \
    rm /usr/lib/modules/*/kernel/drivers/gpu/host1x/host1x.ko.xz

# Regenerate initrd (just in case)
RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver

# Install NVIDIA container toolkit
# netavark is required for podman network to work
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
    sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo && \
    sudo dnf -y install \
      netavark \
      nvidia-container-toolkit && \
    sudo dnf clean all

# Create and enable a systemd service to generate the NVIDIA CDI YAML file
RUN cat <<EOF > /etc/systemd/system/nvidia-cdi.service
[Unit]
Description=Generate the nvidia cdi yaml file
Requires=multi-user.target
Requires=systemd-modules-load.service
After=multi-user.target
After=systemd-modules-load.service

[Service]
Type=oneshot
ExecStartPre=bash -c "echo 1 > /dev/nvgpu/igpu0/power"
ExecStart=nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
RUN systemctl enable nvidia-cdi

# Modify bootc-generic-growpart service to remove virtualization condition
# so that the root partition is expanded to fill the entire disk
RUN sed -i '/ConditionVirtualization=vm/d' /usr/lib/systemd/system/bootc-generic-growpart.service


# Load the i2c-dev kernel module at boot
# for jetson_stats
RUN cat <<EOF > /etc/modules-load.d/i2c-dev.conf
i2c-dev
EOF

# Add kernel arguments for Jetson devices
# disable selinux, and set the correct console device
RUN cat <<EOF > /usr/lib/bootc/kargs.d/10-jetson.toml
kargs = ["console=ttyTCU0,115200"]
EOF

##########

# To enable podman-compose application support
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

# Additional packages
RUN dnf -y install \
            tmux \
            python3-pip \
            git && \
    dnf -y clean all
#            NetworkManager-wifi

### Copy files
COPY files/ /

## Include WIFI config
#RUN --mount=type=secret,id=WIFI_SSID --mount=type=secret,id=WIFI_PASSWORD \
#    sed -i "s/YOUR_WIFI_NAME/$(cat /run/secrets/WIFI_SSID | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection  && \
#    sed -i "s/YOUR_WIFI_PASSWORD/$(cat /run/secrets/WIFI_PASSWORD | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    ln -s /etc/systemd/system/mac-hostname.service /etc/systemd/system/multi-user.target.wants/mac-hostname.service






################################################################################
######################    USER FOR ROOTLESS CONTAINERS  ########################
################################################################################

RUN useradd -m -d /var/home/detector detector && \
    grep video /usr/lib/group | sudo tee -a /etc/group && \
    sudo usermod -aG video detector

RUN mkdir -p /var/home/detector/.config/containers

# Point rootless podman to also look in root's store (read-only)
RUN cat > /var/home/detector/.config/containers/storage.conf <<EOF
[storage]
  driver = "overlay"

[storage.options]
  additionalimagestores = [
    "/var/lib/containers/storage"
  ]
EOF

# Fix ownership (home is /var/home in bootc/ostree)
RUN chown -R detector:detector /var/home/detector/.config


################################################################################
######################    EMBED MODEL    #######################################
################################################################################

RUN mkdir -p /usr/local/share/models/  && \
    curl -L -o /usr/local/share/models/model.pt https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26x.pt

RUN chmod +x /usr/local/bin/export-yolo-onnx.py && \
    pip install ultralytics && \
    python /usr/local/bin/export-yolo-onnx.py /usr/local/share/models/model.pt && \
    chmod 755 -R /usr/local/share/models/

# The .engine file will be created in the first run: [INFO] Building TRT engine from /opt/models/model.onnx (this may take several minutes)

################################################################################
######################    EMBED IMAGES   #######################################
################################################################################

############ Embed image script ############
RUN cat > /usr/bin/embed_image.sh <<EOF
#!/bin/bash
set -euxo pipefail
image=$1
additional_copy_args=${2:-""}
mkdir -p /usr/lib/containers-image-cache
sha=$(echo "$image" | sha256sum | awk '{ print $1 }')
skopeo copy $additional_copy_args --preserve-digests docker://$image dir:/usr/lib/containers-image-cache/$sha
echo "$image,$sha" >> /usr/lib/containers-image-cache/mapping.txt
EOF


############ Copy image script ############
RUN cat > /usr/bin/copy_embedded_images.sh  <<EOF
#!/bin/bash
set -euxo pipefail
while IFS="," read -r image sha
do
	skopeo copy --preserve-digests dir:/usr/lib/containers-image-cache/$sha containers-storage:$image
done < /usr/lib/containers-image-cache/mapping.txt
EOF


############ First boot Copy image script ############
RUN cat > /etc/systemd/system/copy-embedded-images.service  <<EOF
[Unit]
Description=Copy Embedded Images (run once until success)
After=network.target
ConditionPathExists=!/var/lib/copy_embedded_images.done

[Service]
Type=oneshot
ExecStart=/usr/bin/copy_embedded_images.sh
ExecStartPost=/usr/bin/touch /var/lib/copy_embedded_images.done

# Retry if it fails
Restart=on-failure
RestartSec=30

# Important for long-running scripts
TimeoutStartSec=infinity

[Install]
WantedBy=multi-user.target
EOF


############ Script permissions and systemd conf ############
RUN chmod 755 /usr/bin/embed_image.sh && \
    chmod 755 /usr/bin/copy_embedded_images.sh && \
    systemctl enable copy-embedded-images.service


############ Images to embed ############
RUN <<PULL
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-camera-capture:latest
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-inference-tensorrt-jetson:latest
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-stream-viewer:latest
PULL


