[customizations.installer.kickstart]
contents = '''
network --bootproto=dhcp --device=link --activate --onboot=on
zerombr

user --name=admin --password=$6$nRAle.gs2bcemfTO$n706swfUtMOVfIZ2QngZCQD4OWGoOwWhAYvbzh1zPuMgD1t.Qo6b.3LQPcoVNZnQZ7RjIJi43Jik1VMbRiR.B/ --groups=wheel --iscrypted

# Dynamic partitioning
%pre --interpreter=/bin/bash --log=/root/ks-pre.log
set -e

# Detect the first non-removable physical disk
DISK=$(lsblk -ndo NAME,TYPE,RO,RM | awk '$2=="disk" && $3==0 && $4==0 {print "/dev/"$1; exit}')
TOTAL=$(blockdev --getsize64 "$DISK")
LVMS_SIZE_MIB=$(( TOTAL * 30 / 100 / 1048576 ))
SYSROOT_SIZE_MIB=$(( TOTAL * 15 / 100 / 1048576 ))

cat <<EOF > /tmp/dynamic-partition.ks
# Boot partition (unencrypted)
part /boot --size=1024 --fstype=xfs --ondisk=$(basename $DISK)

# Encrypted physical volume for LVM
part pv.01 --size=10000 --grow --maxsize=${LVMS_SIZE_MIB} --encrypted --passphrase="redhat" --ondisk=$(basename $DISK)

# LVM setup inside the encrypted PV
volgroup vg_system pv.01
logvol / --vgname=vg_system --size=${SYSROOT_SIZE_MIB} --name=root --fstype=xfs
logvol swap --vgname=vg_system --size=2048 --name=swap
EOF
%end

%include /tmp/dynamic-partition.ks

%post --log=/root/ks-post.log
%end

reboot --eject
'''