ARG BASE_IMAGE_TAG='9.6'
ARG USHIFT_VER='4.20'
########################################

FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

ARG USHIFT_VER

RUN dnf config-manager \
        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms

RUN dnf install -y firewalld microshift lvm2 cryptsetup clevis clevis-luks clevis-tpm2 tpm2-tools udev && \
    systemctl enable microshift && \
    dnf clean all

# Mandatory firewall configuration
RUN firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1

# Copy files into the image
COPY files/ /

RUN chmod +x /usr/local/sbin/* && \
    systemctl enable /etc/systemd/system/microshift-*.service || true
