ARG BASE_IMAGE_TAG='9.6'
ARG USHIFT_VER='4.20'
########################################

FROM registry.redhat.io/rhel9/rhel-bootc:${BASE_IMAGE_TAG}

################################################################################
#Red Hat Edge Manager
################################################################################
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Optional: To enable podman-compose application support, uncomment below
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

################################################################################


ARG USHIFT_VER

RUN dnf config-manager \
        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms

# Install packages with systemd-cryptenroll instead of Clevis
RUN dnf install -y firewalld microshift microshift-cert-manager microshift-olm dialog \
    systemd cryptsetup tpm2-tools tpm2-tss pciutils \
    systemd-udev dracut && \
    systemctl enable microshift && \
    dnf clean all

RUN firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1 && \
    firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=80/tcp && \
    firewall-offline-cmd --zone=public --add-port=443/tcp && \
    firewall-offline-cmd --zone=public --add-port=6443/tcp && \
    firewall-offline-cmd --zone=public --add-port=30000-32767/tcp

# Copy files into the image
COPY files/ /

RUN chmod +x /usr/local/sbin/* && \
    ln -s /usr/lib/systemd/system/mac-hostname.service /etc/systemd/system/multi-user.target.wants/mac-hostname.service && \
    ln -s /usr/lib/systemd/system/microshift-dynamic-conf.service /etc/systemd/system/multi-user.target.wants/microshift-dynamic-conf.service && \
    ln -s /usr/lib/systemd/system/microshift-make-rshared.service /etc/systemd/system/multi-user.target.wants/microshift-make-rshared.service

# Generate new initramfs.img with systemd-cryptenroll support
# Note: 'systemd' module includes systemd-cryptsetup functionality automatically
RUN set -xe; \
    kver=$(ls /usr/lib/modules | sort -Vr | head -n1); \
    dracut --force --add "crypt systemd tpm2-tss" \
           --install "systemd-cryptenroll systemd-cryptsetup cryptsetup" \
           --no-hostonly \
           /usr/lib/modules/$kver/initramfs.img "$kver"