FROM ghcr.io/luisarizmendi/bootc-rhel-jetson:latest

##########

# To enable podman-compose application support
 RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
     dnf -y install podman-compose && \
     dnf -y clean all && \
     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
     systemctl enable podman.service

# Additional packages
RUN dnf -y install \
            tmux \
            python3-pip \
            git && \
    dnf -y clean all
#            NetworkManager-wifi

### Copy files
COPY files/ /

## Include WIFI config
#RUN --mount=type=secret,id=WIFI_SSID --mount=type=secret,id=WIFI_PASSWORD \
#    sed -i "s/YOUR_WIFI_NAME/$(cat /run/secrets/WIFI_SSID | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection  && \
#    sed -i "s/YOUR_WIFI_PASSWORD/$(cat /run/secrets/WIFI_PASSWORD | tr -d '\n')/g" /etc/NetworkManager/system-connections/wifi.nmconnection

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    ln -s /etc/systemd/system/mac-hostname.service /etc/systemd/system/multi-user.target.wants/mac-hostname.service






################################################################################
######################    USER FOR ROOTLESS CONTAINERS  ########################
################################################################################

RUN useradd -m -d /var/home/detector detector && \
    grep video /usr/lib/group | sudo tee -a /etc/group && \
    sudo usermod -aG video detector

RUN mkdir -p /var/home/detector/.config/containers

# Point rootless podman to also look in root's store (read-only)
RUN cat > /var/home/detector/.config/containers/storage.conf <<EOF
[storage]
  driver = "overlay"

[storage.options]
  additionalimagestores = [
    "/var/lib/containers/storage"
  ]
EOF

# Fix ownership (home is /var/home in bootc/ostree)
RUN chown -R detector:detector /var/home/detector/.config


RUN mkdir -p /var/home/detector/.config/containers/systemd && \
    cp /tmp/quadlets/object-detection-custom-camera-capture.container /var/home/detector/.config/containers/systemd/ && \
    cp /tmp//quadlets/object-detection-custom-stream-viewer.container  /var/home/detector/.config/containers/systemd/ && \
    cp /tmp//quadlets/object-detection-custom-inference-tensorrt-jetson.container   /var/home/detector/.config/containers/systemd/ 


################################################################################
######################    EMBED MODEL    #######################################
################################################################################

RUN mkdir -p /usr/local/share/models/  && \
    curl -L -o /usr/local/share/models/model.pt https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26x.pt

RUN chmod +x /usr/local/bin/export-yolo-onnx.py && \
    pip install ultralytics && \
    python /usr/local/bin/export-yolo-onnx.py /usr/local/share/models/model.pt && \
    chmod 755 -R /usr/local/share/models/

# The .engine file will be created in the first run: [INFO] Building TRT engine from /opt/models/model.onnx (this may take several minutes)

################################################################################
######################    EMBED IMAGES   #######################################
################################################################################

############ Embed image script ############
RUN cat > /usr/bin/embed_image.sh <<'EOF'
#!/bin/bash
set -euxo pipefail
image=$1
additional_copy_args=${2:-""}
mkdir -p /usr/lib/containers-image-cache
sha=$(echo "$image" | sha256sum | awk '{ print $1 }')
skopeo copy $additional_copy_args --preserve-digests docker://$image dir:/usr/lib/containers-image-cache/$sha
echo "$image,$sha" >> /usr/lib/containers-image-cache/mapping.txt
EOF

############ Copy image script ############
RUN cat > /usr/bin/copy_embedded_images.sh <<'EOF'
#!/bin/bash
set -euxo pipefail
while IFS="," read -r image sha
do
    skopeo copy --preserve-digests dir:/usr/lib/containers-image-cache/$sha containers-storage:$image
done < /usr/lib/containers-image-cache/mapping.txt
EOF


############ First boot Copy image script ############
RUN cat > /etc/systemd/system/copy-embedded-images.service  <<EOF
[Unit]
Description=Copy Embedded Images (run once until success)
After=network.target
ConditionPathExists=!/var/lib/copy_embedded_images.done

[Service]
Type=oneshot
ExecStart=/usr/bin/copy_embedded_images.sh
ExecStartPost=/usr/bin/touch /var/lib/copy_embedded_images.done

# Retry if it fails
Restart=on-failure
RestartSec=30

# Important for long-running scripts
TimeoutStartSec=infinity

[Install]
WantedBy=multi-user.target
EOF


############ Script permissions and systemd conf ############
RUN chmod 755 /usr/bin/embed_image.sh && \
    chmod 755 /usr/bin/copy_embedded_images.sh && \
    systemctl enable copy-embedded-images.service


############ Images to embed ############
RUN <<PULL
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-camera-capture:latest
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-inference-tensorrt-jetson:latest
/usr/bin/embed_image.sh  quay.io/luisarizmendi/object-detection-custom-stream-viewer:latest
PULL


