FROM ghcr.io/luisarizmendi/bootc-rhel-jetson:latest

##########
# To enable podman-compose application support
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf -y install podman-compose && \
    dnf -y clean all && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
    systemctl enable podman.service

# Additional packages
RUN dnf -y install \
            tmux \
            python3-pip \
            git && \
    dnf -y clean all

### Copy files
COPY files/ /

RUN chmod -R 600 /etc/NetworkManager/system-connections/ && \
    chmod +x /usr/local/bin/set-hostname-from-mac.sh && \
    systemctl enable mac-hostname.service

################################################################################
######################    USER FOR ROOTLESS CONTAINERS  ########################
################################################################################

RUN useradd -M -d /var/home/detector detector && \
    grep video /usr/lib/group | tee -a /etc/group && \
    usermod -aG video detector

RUN groupadd -r -g 980 gpu && \
    usermod -aG gpu detector

RUN groupadd -r cstore && \
    usermod -aG cstore detector

# Required for user sessions
RUN systemctl enable systemd-logind.service

# Required for /run/user/1000 — use UID, not username
RUN systemctl enable user-runtime-dir@1000.service

RUN systemctl enable tegra-dev-perms.service


################################################################################
######################    EMBED MODEL    #######################################
################################################################################

################################################################################
######################    EMBED IMAGES   #######################################
################################################################################

############ Script permissions and systemd enable ############
RUN chmod 755 /usr/local/bin/embed_image.sh && \
    chmod 755 /usr/local/bin/copy_embedded_images.sh && \
    systemctl enable copy-embedded-images.service

############ Images to embed ############
RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-camera-capture:latest --user detector
RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-inference-tensorrt-jetson:latest --user detector
RUN /usr/local/bin/embed_image.sh quay.io/luisarizmendi/object-detection-custom-stream-viewer:latest --user detector